/* ------------------------------------------------------------------------- *
 * CRC-32 Version 2.0.0 by Craig Bruce, 2006-04-29.
 *
 * The CRC-32 values generated by this program are the same CRC-32 values used
 * by GZIP, PKZIP and ZMODEM.
 *
 * Based on the byte-oriented implementation "File Verification using CRC"
 * by Mark. Nelson in Dr. Dobb's Journal, May 1992, pp. 64-67.
 *
 * THIS PROGRAM IS PUBLIC-DOMAIN SOFTWARE
 *
 * Rewritten as a C++ Class by DIBGazo <tuldok89@gmail.com>
 * ------------------------------------------------------------------------- */

#include "crc32.h"
#include "lz_crc32.h"

#include <QtGlobal>

//!
//! \brief Constructor
//!
CRC32::CRC32() : m_crc32(0)
{
}

//!
//! \brief Destructor
//!
CRC32::~CRC32()
{
}


//!
//! \brief          Accumulate the CRC-32 value of a buffer
//! \param buffer   Buffer to compute CRC-32 value for
//! \param bufsize  number of bytes in buffer
//!
void CRC32::Update(quint8 *buffer, quint32 bufsize)
{
    m_crc32 = lzma_crc32(buffer, bufsize, m_crc32);
}

//!
//! \brief  Get the accumulated CRC-32 value
//! \return CRC-32
//!
unsigned int CRC32::GetChecksum() const
{
    return m_crc32;
}
